variable "project_name" {}
variable "region" {}
variable "instance_type" {}
variable "key_pair_name" {}
variable "public_key_path" {}
variable "private_key_path" {}
variable "ssl_domain" {}
variable "influx_admin_pw" {}
variable "influx_user_pw" {}
variable "grafana_admin_pw" {}
